CREATE TABLE IF NOT EXISTS rec_huagao_request_log (
  request_id VARCHAR(64) NOT NULL COMMENT '请求ID',
  query_key VARCHAR(64) DEFAULT NULL COMMENT '查询上下文哈希',
  scene VARCHAR(50) NOT NULL COMMENT '场景',
  user_id BIGINT DEFAULT NULL COMMENT '用户ID',
  visitor_id VARCHAR(64) DEFAULT NULL COMMENT '匿名访客ID',
  session_id VARCHAR(64) DEFAULT NULL COMMENT '会话ID',
  keyword VARCHAR(255) DEFAULT NULL COMMENT '原始搜索词',
  normalized_keyword VARCHAR(255) DEFAULT NULL COMMENT '标准化搜索词',
  fenlei VARCHAR(100) DEFAULT NULL COMMENT '分类筛选',
  tag_id BIGINT DEFAULT NULL COMMENT '系统标签筛选ID',
  page_no BIGINT NOT NULL COMMENT '页码',
  page_size BIGINT NOT NULL COMMENT '分页大小',
  sort_mode VARCHAR(50) NOT NULL COMMENT '排序模式',
  has_search TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否搜索',
  has_fenlei_filter TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否分类筛选',
  has_tag_filter TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否标签筛选',
  result_total BIGINT NOT NULL DEFAULT 0 COMMENT '命中总数',
  returned_count BIGINT NOT NULL DEFAULT 0 COMMENT '本页返回数',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (request_id),
  KEY idx_rec_hg_req_scene_created (scene, created_at),
  KEY idx_rec_hg_req_user_created (user_id, created_at),
  KEY idx_rec_hg_req_visitor_created (visitor_id, created_at),
  KEY idx_rec_hg_req_query_created (query_key, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='画稿请求日志';

CREATE TABLE IF NOT EXISTS rec_huagao_impression_log (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  request_id VARCHAR(64) NOT NULL COMMENT '请求ID',
  huagao_id BIGINT NOT NULL COMMENT '画稿ID',
  shangjia_id BIGINT DEFAULT NULL COMMENT '画师ID',
  position INT NOT NULL COMMENT '曝光位置',
  page_no BIGINT NOT NULL COMMENT '页码',
  page_size BIGINT NOT NULL COMMENT '分页大小',
  scene VARCHAR(50) NOT NULL COMMENT '场景',
  keyword VARCHAR(255) DEFAULT NULL COMMENT '原始搜索词',
  normalized_keyword VARCHAR(255) DEFAULT NULL COMMENT '标准化搜索词',
  fenlei VARCHAR(100) DEFAULT NULL COMMENT '分类筛选',
  tag_id BIGINT DEFAULT NULL COMMENT '系统标签筛选ID',
  search_score INT DEFAULT NULL COMMENT '搜索分',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_rec_hg_imp_req_item (request_id, huagao_id),
  KEY idx_rec_hg_imp_item_created (huagao_id, created_at),
  KEY idx_rec_hg_imp_scene_created (scene, created_at),
  KEY idx_rec_hg_imp_req (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='画稿曝光日志';

CREATE TABLE IF NOT EXISTS rec_huagao_action_log (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  event_id VARCHAR(64) NOT NULL COMMENT '事件幂等ID',
  event_type VARCHAR(50) NOT NULL COMMENT '事件类型',
  request_id VARCHAR(64) DEFAULT NULL COMMENT '请求ID',
  huagao_id BIGINT NOT NULL COMMENT '画稿ID',
  shangjia_id BIGINT DEFAULT NULL COMMENT '画师ID',
  user_id BIGINT DEFAULT NULL COMMENT '用户ID',
  visitor_id VARCHAR(64) DEFAULT NULL COMMENT '匿名访客ID',
  session_id VARCHAR(64) DEFAULT NULL COMMENT '会话ID',
  position INT DEFAULT NULL COMMENT '曝光位置',
  scene VARCHAR(50) DEFAULT NULL COMMENT '场景',
  source VARCHAR(50) DEFAULT NULL COMMENT '来源',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_rec_hg_action_event (event_id),
  KEY idx_rec_hg_action_item_created (huagao_id, created_at),
  KEY idx_rec_hg_action_type_created (event_type, created_at),
  KEY idx_rec_hg_action_req (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='画稿行为日志';

CREATE TABLE IF NOT EXISTS rec_huagao_item_stat_daily (
  dt DATE NOT NULL COMMENT '统计日期',
  huagao_id BIGINT NOT NULL COMMENT '画稿ID',
  shangjia_id BIGINT DEFAULT NULL COMMENT '画师ID',
  impression_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '曝光数',
  click_detail_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '详情点击数',
  favorite_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '收藏数',
  search_impression_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '搜索曝光数',
  filter_fenlei_impression_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '分类筛选曝光数',
  filter_tag_impression_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '标签筛选曝光数',
  search_click_detail_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '搜索详情点击数',
  search_favorite_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '搜索收藏数',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (dt, huagao_id),
  KEY idx_rec_hg_item_daily_artist (shangjia_id, dt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='画稿日聚合统计';

CREATE TABLE IF NOT EXISTS rec_huagao_query_stat_daily (
  dt DATE NOT NULL COMMENT '统计日期',
  query_key VARCHAR(64) NOT NULL COMMENT '查询上下文哈希',
  scene VARCHAR(50) NOT NULL COMMENT '场景',
  keyword VARCHAR(255) DEFAULT NULL COMMENT '原始搜索词',
  normalized_keyword VARCHAR(255) DEFAULT NULL COMMENT '标准化搜索词',
  fenlei VARCHAR(100) DEFAULT NULL COMMENT '分类筛选',
  tag_id BIGINT DEFAULT NULL COMMENT '系统标签筛选ID',
  has_search TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否搜索',
  has_fenlei_filter TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否分类筛选',
  has_tag_filter TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否标签筛选',
  request_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '请求数',
  impression_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '曝光数',
  click_detail_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '详情点击数',
  favorite_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '收藏数',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (dt, query_key),
  KEY idx_rec_hg_query_daily_scene (scene, dt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='画稿查询日聚合统计';
